apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: node-app
  template:
    metadata:
      labels:
        app: node-app
    spec:
      containers:
        - name: node-app
          image: devops-project:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 4000
          env:
            - name: MONGODB_URI
              value: mongodb://mongo:27017/test_db
---
apiVersion: v1
kind: Service
metadata:
  name: node-app
spec:
  selector:
    app: node-app
  ports:
    - port: 4000
      targetPort: 4000
  type: NodePort
